### ISSUE TITLE
1回目の ISC Japan Meetup を開催

### ISSUE THREAD

**Issue by yuhattor** [InnerSourceCommons/jp-roadmap#29]
https://innersourcecommons.connpass.com/event/257580/

こちらで開催予定です。

---
# InnerSource Commons Japan 始動!!

**インナーソース (InnerSource)** をご存知でしょうか。インナーソースは**オープンソースの開発スタイルを企業内で実践する取り組み**のことです。インナーソースを開発に取り入れると**ソフトウェア開発のスピードや品質が向上**するだけでなく、**縦割りの仕組みを抱える企業でサイロ化**してしまった開発チームが、**開発文化を変革する**ことにも繋がります :rocket:

この度、インナーソースや内製化、コード共有文化に関する情報交換を日本語で行うコミュニティとして、**InnerSource Commons Japan** を立ち上げました:party_popper::party_popper::party_popper:

本ミートアップはコミュニティ勉強会の第一回となります！

InnerSource は様々な場所で起こっています。[こちら](https://innersourcecommons.org/stories/)で紹介されている事例をぜひご覧ください！

[![](https://yukihattori.blob.core.windows.net/public/innersource-companies.png)](https://twitter.com/InnerSourceOrg/status/1270729207988006912/photo/1)

## 組織のサイロを壊す "インナーソース" とは、そして InnerSource Commons とは

**インナーソース**という言葉は 2000年にエンジニアリングの方法論のひとつとしてTim O'Reilly 氏が考案した言葉です。しかし当時は少なくとも **インナーソース** というコンセプトが企業に広く浸透することはありませんでした。一方で、**内製化**の文脈では **コード共有** や **共創** などの言葉を介して同様のテーマが語られてきましたし、オープンソースの文脈では組織のOSS活用に関する取り組みである **OSPO** が認知度を上げています。そして SaaS やクラウドの文脈では **GitHub** や **GitLab** の活用に伝統的な大企業も目を向け始めています:eyes:

**InnerSource Commons** はそれらの別々の文脈で違う言葉を使って語られてきた活動を **インナーソース** という共通認識のもとに体系化し、実践者のプラクティスをまとめて普及する活動をしています。

日本のコミュニティは立ち上がったばかりです。インナーソースの活動は、内製化・コード共有・共創・CCoE・GitHub 活用・オープンソース活用など、様々な活動にリンクします。**コミュニティはとてもオープンで、有志のボランティアにより支えられています。興味のある方はぜひイベントにお立ち寄りください！**

より詳しい情報に関しては[こちらの資料](https://yukihattori.blob.core.windows.net/public/InnerSourceCommonsJapan.pdf)や、[connpass の InnerSource Commons ページ](http://innersourcecommons.connpass.com)からご参照ください。また、英語ですがInnerSource Commons の[公式ページ](https://innersourcecommons.org/)にも詳しい情報が掲載されています。

[![](https://pbs.twimg.com/media/EVpmyaZUUAIrWHP?format=jpg)](https://twitter.com/InnerSourceOrg/status/1250425375110230016)

## イベント Agenda

| 時間           | コンテンツ                                                                                               |
| -------------- | -------------------------------------------------------------------------------------------------------- |
| 19:00 - 19:10  | 開場・オープニング                                                                                       |
| 19:10 - 19:30  | インナーソース / InnerSource Commons とは (@yuhattor)                                                    |
| 19:30 - 20:10  | **インナーソースのはじめかた**<br> インナーソースってなに？どこから始めれば良いの？インナーソースの入門セッションです。基本的な概念から、実績に裏付けされた "インナーソースパターン" まで、インナーソースパターンブックの訳者がお届けします (@yuhattor) |
| 20:10 - 20:20  | 休憩、雑談                                                                                               |
| 20:20 - 20:40  | **「インナーソース入門」で入門できるのか？**<br>インナーソース入門 (原題: Getting Started with InnerSource) を読めばインナーソースに入門できるのか？一人の読者として、協働に焦点を当てていた元実務者として、関連文献も参照しながら探っていきます。 (@masskaneko)                           |
| 20:40 -        | QA、クロージング (会は21:00 まで開けますので、雑談する方はどうぞ)                                        |

**2回以降はインナーソースの実践者や、現在コミュニティで翻訳中の ["Getting Started with InnerSource"(邦題「InnerSource 入門(仮)」](https://github.com/InnerSourceCommons/jp-contents/blob/main/Getting-Started-with-InnerSource/ja.md) の翻訳者たちによる解説など、インナーソースに関する情報をお届けしてまいります！**

### スピーカー紹介

![](https://yukihattori.blob.core.windows.net/public/profile.small.png)

**服部 佑樹 (@yuhattor)** | [Twitter](https://twitter.com/yuhattor) | [GitHub](https://github.com/yuhattor) | [Linkedin](https://www.linkedin.com/in/yukihattori/)

Microsoft で Cloud Solution Architect をやっています。**InnerSource Commons Japan** の発起人です。

- InnerSource Commons - [InnerSource Patterns Trusted Committer](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/TRUSTED-COMMITTERS.md)
- [InnerSource Patterns](https://patterns.innersourcecommons.org/v/jp/) の日本語翻訳
- CTO協会 Day One[「今後確実に必要になる InnerSource - GitHub と Microsoft の Day One
」](https://www.youtube.com/watch?v=wQSb3gK5iBY)
- Developer Summit 2021 [「MicrosoftがGitHubで実践するインナーソースの取り組みとは？」](https://codezine.jp/article/detail/13685)

![](https://yukihattori.blob.core.windows.net/public/masskaneko.png)

**金子昌永 (@masskaneko)** | [Twitter](https://twitter.com/masskaneko) | [GitHub](https://github.com/masskaneko) | [Linkedin](https://www.linkedin.com/in/masanori-kaneko-45609042/)

キャリアの4割はソフトウェア開発者、6割は品質と協働をテーマに支援するエンジニア。
現在は定職から退き、コミュニティ活動と畑仕事に勤しむ。

- InnerSource Commons Japan - [Trusted Committer](https://github.com/InnerSourceCommons/jp-contents/blob/main/TRUSTED-COMMITTERS.md)
- 共訳: [実践ソフトウェアエンジニアリング第9版, オーム社, 2021](https://www.ohmsha.co.jp/book/9784274227943/)
- 講演: [ET&IoT2021 米国修士過程ベストセラーに学ぶ体系的ソフトウェアエンジニアリングの必要性](https://docs.google.com/presentation/d/1Xoq5J8_X3aKDkFHbldwFDIpm2XtyyUwLSyEeTL4xCZQ/edit#slide=id.p)

## 参加方法

URLは本イベントに参加登録いただいた方に、このページでご案内いたします。

Twitter で #InnerSource のハッシュタグをつけてコメントいただけますと幸いです。

## Code of Conduct / 行動規範
すべての参加者が居心地よく安全に過ごせる環境を保てるようご協力をお願いします。

性別、人種、国籍、性的指向、または身体の障碍などいかなる理由においても、相手の尊厳を傷つけるような行為は許されません。

もし、そのようなご懸念、ハラスメント行為、疑わしい行動または破壊的な行動について気になることがございましたら、イベント主催までお知らせください。主催の判断により、該当者の退室、参加の巨費など対応を求め実行します。

**Comment by bory-kb** [comment]
メモ
Connpass のイベントページに Slack のインバイトリンク等々含めたほうがよさそうですね。
（今は Connpass の ISC Japan グループページにしかなさそうだったので）

**Comment by yuhattor** [comment]
そうですね！
